# Generated by Django 4.2.11 on 2024-06-03 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_patientrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientRecord_Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifier', models.CharField(max_length=50)),
                ('patient_id', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('doctor_id', models.CharField(max_length=50)),
                ('diagnosis', models.TextField()),
            ],
        ),
    ]
