# Generated by Django 4.2.11 on 2024-04-28 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="cal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value_a", models.CharField(max_length=10)),
                ("value_b", models.CharField(max_length=10)),
                ("result", models.CharField(max_length=10)),
            ],
        ),
    ]
